package com.app.notificationmodule.consumer;

import com.app.notificationmodule.payload.OrderEvent;
import com.app.notificationmodule.service.SendNotification;
import lombok.RequiredArgsConstructor;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Service;
import java.util.function.Consumer;

@Service
@RequiredArgsConstructor
public class OrderConsumer {


    private final SendNotification sendNotification;

    @Bean
    public Consumer<OrderEvent> orderEventConsumer()
    {
        return orderEvent -> {
            String status = orderEvent.getStatus().toString();
            switch (status){
                case "CREATED" -> System.out.println("Created: ");
                case "DELIVERED" -> System.out.println("Delivered: ");
                case "CANCELLED" -> System.out.println("Cancelled: ");
                case "COMPLETED" -> System.out.println("Completed: ");
                case "CONFIRMED" -> System.out.println("CONFIRMED: ");
                case "SHIPPED" -> System.out.println("SHIPPED: ");
            }
            System.out.println("Order -> \nID: "+ orderEvent.getId()+"\nSTATUS: "+orderEvent.getStatus()+"\nITEMS: "+orderEvent.getOrderItems().toString());
            try{
                String message = "Order -> \nID: "+ orderEvent.getId()+"\nITEMS: "+orderEvent.getOrderItems().toString();
                String body = """
                        Your order is %S .
                        %s.
                        
                        In case of any grivences contact:
                        email: pandaishon@gmail.com
                        ph: 9474306285
                        =^._.^=
                        
                         ___________________________________________________ 
                        |                                                   |
                        |   Thank you for testing this project. Hire me!    |
                        |   This is an autogenerated email. Do not reply.   |
                        |___________________________________________________|
                        """.formatted(orderEvent.getStatus().name(),message);
                sendNotification.send(orderEvent.getEmail(),orderEvent.getStatus().name(),body);
                System.out.println("MAIL SENT");
            }catch (Exception e)
            {
                System.out.println("MAIL not sent.");
            }
        };
    }
}
