#Spring
spring:
    #MessageQueue
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    connection-timeout: 30000
    virtual-host: ${RABBITMQ_VHOST}
  cloud:
    refresh:
      never-refreshable:
        - com.netflix.discovery.EurekaClient
        - com.netflix.discovery.DiscoveryClient
        - org.springframework.cloud.config.server.config.ConfigServerHealthIndicator
    #Stream ->
    function:
      definition: orderEventConsumer
    stream:
      bindings:
        orderEventConsumer-in-0:
          destination: ecomm.exchange.order
          group: notification
#
#      kafka:
#        binder:
#          brokers: localhost:9092
      rabbit:
        bindings:
          orderEventConsumer-in-0:
              consumer:
                binding-routing-key: order.*

#Notification Queue and Exchange
#rabbitmq:
#  exchange:
#    name: ecomm.exchange
#  queue:
#    name: notification.queue
#  routing:
#    order: order.*

#Logging
logging:
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{traceId}] %logger{36} - %msg%n'
  level:
    root: INFO
  file:
    name: Logs/${spring.application.name}.log

#Eureka
eureka:
  client:
    refresh:
      enable: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    hostname: localhost
    instanceId: ${spring.application.name}:${server.port}

#Server
server:
  port: 8085
