#Spring
spring:
  #Database POSTGRES
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: "ishon"
    password: "ishon"
  jpa:
    hibernate:
      ddl-auto: update
    #MessageQueue
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,busrefresh,refresh

#Server
server:
  port: 8083
