#Spring
spring:
  #Database -> MongoDB
  mongodb:
    uri: mongodb://localhost:27017/userDB
    database: userDB
  #MessageQueue
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

#Logging
logging:
  level:
    root: DEBUG


#Server
server:
  port: 8082

