#Spring
spring:
  #Database -> MongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/userDB
      database: userDB
  #MessageQueue
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    connection-timeout: 30000
    virtual-host: ${RABBITMQ_VHOST}
  cloud:
    refresh:
      never-refreshable:
        - com.netflix.discovery.EurekaClient
        - com.netflix.discovery.DiscoveryClient
        - org.springframework.cloud.config.server.config.ConfigServerHealthIndicator

#Actuator + Zipkin
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,busrefresh,refresh,prometheus
  tracing:
    sampling:
      probability: 1.0

#Eureka
eureka:
  client:
    refresh:
      enable: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    hostname: localhost
    instanceId: ${spring.application.name}:${server.port}

#Logging
logging:
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{traceId}] %logger{36} - %msg%n'
  level:
    root: INFO
  file:
    name: Logs/${spring.application.name}.log

#Server
server:
  port: 8082

