#Spring
spring:
  application:
    name: ConfigServer
  ## Config Server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: file:///C:\Users\Admin\Desktop\CAREER\PROJECTS\FAISAL_SPRING\Ecommerce Udemy\microservice_backend\ConfigServer\src\main\resources\config
          search-locations: file:///home/ishonpanda/Desktop/CAREER/PROJECTS/ECOMM/Ecomm-microservice/ConfigServer/src/main/resources/config
          
  ## MessageQueue
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#Actuator
management:
  endpoint:
    shutdown:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,info,metrics,busrefresh,refresh,shutdown

#Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

#Logging
logging:
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{traceId}] %logger{36} - %msg%n'
  level:
    root: INFO
  file:
    name: Logs/${spring.application.name}.log


#Server
server:
  port: 8888