spring:
  application:
    name: producer
  cloud:
    function:
      definition: sendLocation;statusUpdate
    stream:
      poller:
        fixed-delay: 1000
      bindings:
        sendLocation-out-0:
          destination: riderEvent
          content-type: application/json

        statusUpdate-out-0:
          destination: riderEvent
          content-type: text/plain
      kafka:
        binder:
          brokers: localhost:9092



#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.add.type.headers: false
